// ============================================================
// CatalogData.js
// B2B Merchandising Catalog — 65 Products
// Categories: Apparel | Uniform & Workwear | Sportswear
// ============================================================
export const catalogData = [
  // ============================================================
  // APPAREL COLLECTION
  // ============================================================
  // ── Casual Wear ─────────────────────────────────────────────
  {
    id: 1,
    name: "Hoodies",
    category: "Apparel",
    subCategory: "Casual Wear",
    price: "$24.99",
    image: "/src/assets/Hoodie black.png",
    localImageName: "Hoodie black.png",
    standardColors: ["Navy Blue", "Black", "Charcoal", "Forest Green", "Burgundy"],
    colorImages: {
      "Black": "/src/assets/Hoodie black.png"
    },
  },
  {
    id: 2,
    name: "T-Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    price: "$12.99",
    image: "https://picsum.photos/seed/casualtshirt/400/300",
    localImageName: "t-shirts.jpg",
    standardColors: ["White", "Black", "Navy Blue", "Grey Melange", "Sky Blue"],
    colorImages: {},
  },
  {
    id: 3,
    name: "Polo Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    price: "$19.99",
    image: "https://picsum.photos/seed/casualpolo/400/300",
    localImageName: "polo-shirts.jpg",
    standardColors: ["White", "Navy Blue", "Royal Blue", "Black", "Bottle Green"],
    colorImages: {},
  },
  {
    id: 4,
    name: "Long Sleeve T-Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    price: "$16.99",
    image: "https://picsum.photos/seed/longsleeve/400/300",
    localImageName: "long-sleeve-t-shirts.jpg",
    standardColors: ["Black", "White", "Heather Grey", "Navy Blue", "Olive Green"],
    colorImages: {},
  },
  {
    id: 5,
    name: "Henley Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    price: "$18.99",
    image: "https://picsum.photos/seed/henleyshirt/400/300",
    localImageName: "henley-shirts.jpg",
    standardColors: ["Cream White", "Charcoal", "Slate Blue", "Burgundy", "Olive"],
    colorImages: {},
  },
  {
    id: 6,
    name: "Zip-Up Hoodies",
    category: "Apparel",
    subCategory: "Casual Wear",
    price: "$29.99",
    image: "https://picsum.photos/seed/zipuphoodie/400/300",
    localImageName: "zip-up-hoodies.jpg",
    standardColors: ["Black", "Charcoal", "Navy Blue", "Dark Red", "Stone Grey"],
    colorImages: {},
  },
  {
    id: 7,
    name: "Casual Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    price: "$21.99",
    image: "https://picsum.photos/seed/casualshirt/400/300",
    localImageName: "casual-shirts.jpg",
    standardColors: ["Light Blue", "White", "Pale Pink", "Sage Green", "Mustard Yellow"],
    colorImages: {},
  },
  // ── Loungewear ──────────────────────────────────────────────
  {
    id: 8,
    name: "Sweatshirts",
    category: "Apparel",
    subCategory: "Loungewear",
    price: "$22.99",
    image: "https://picsum.photos/seed/sweatshirt/400/300",
    localImageName: "sweatshirts.jpg",
    standardColors: ["Heather Grey", "Black", "Dusty Rose", "Navy Blue", "Sage Green"],
    colorImages: {
      "Heather Grey": "/src/assets/White sweatshirt.png",
    },
  },
  {
    id: 9,
    name: "Fleece Trousers / Joggers",
    category: "Apparel",
    subCategory: "Loungewear",
    price: "$19.99",
    image: "https://picsum.photos/seed/fleecejogger/400/300",
    localImageName: "fleece-trousers-joggers.jpg",
    standardColors: ["Charcoal", "Black", "Heather Grey", "Navy Blue", "Oatmeal"],
    colorImages: {},
  },
  {
    id: 10,
    name: "Sweatpants",
    category: "Apparel",
    subCategory: "Loungewear",
    price: "$17.99",
    image: "https://picsum.photos/seed/sweatpants/400/300",
    localImageName: "sweatpants.jpg",
    standardColors: ["Black", "Heather Grey", "Navy Blue", "Dark Olive", "Stone"],
    colorImages: {},
  },
  {
    id: 11,
    name: "Shorts",
    category: "Apparel",
    subCategory: "Loungewear",
    price: "$14.99",
    image: "https://picsum.photos/seed/casualshorts/400/300",
    localImageName: "shorts.jpg",
    standardColors: ["Navy Blue", "Khaki", "Black", "Heather Grey", "Forest Green"],
    colorImages: {},
  },
  {
    id: 12,
    name: "Tank Tops",
    category: "Apparel",
    subCategory: "Loungewear",
    price: "$11.99",
    image: "https://picsum.photos/seed/tanktop/400/300",
    localImageName: "tank-tops.jpg",
    standardColors: ["White", "Black", "Heather Grey", "Navy Blue", "Blush Pink"],
    colorImages: {},
  },
  {
    id: 13,
    name: "Pyjamas and Loungewear",
    category: "Apparel",
    subCategory: "Loungewear",
    price: "$26.99",
    image: "https://picsum.photos/seed/pyjamas/400/300",
    localImageName: "pyjamas-and-loungewear.jpg",
    standardColors: ["Light Blue", "Cream White", "Soft Pink", "Sage Green", "Lavender"],
    colorImages: {},
  },
  // ── Knitwear ────────────────────────────────────────────────
  {
    id: 14,
    name: "Jackets",
    category: "Apparel",
    subCategory: "Knitwear",
    price: "$39.99",
    image: "https://picsum.photos/seed/casualjacket/400/300",
    localImageName: "jackets.jpg",
    standardColors: ["Black", "Camel", "Navy Blue", "Olive Green", "Burgundy"],
    colorImages: {},
  },
  {
    id: 15,
    name: "Vests",
    category: "Apparel",
    subCategory: "Knitwear",
    price: "$27.99",
    image: "https://picsum.photos/seed/knitwear vest/400/300",
    localImageName: "vests.jpg",
    standardColors: ["Camel", "Charcoal", "Navy Blue", "Burgundy", "Forest Green"],
    colorImages: {},
  },
  {
    id: 16,
    name: "Chinos and Casual Trousers",
    category: "Apparel",
    subCategory: "Knitwear",
    price: "$29.99",
    image: "https://picsum.photos/seed/chinotrousers/400/300",
    localImageName: "chinos-and-casual-trousers.jpg",
    standardColors: ["Khaki", "Navy Blue", "Olive Green", "Stone", "Black"],
    colorImages: {},
  },
  {
    id: 17,
    name: "Cargo Pants",
    category: "Apparel",
    subCategory: "Knitwear",
    price: "$31.99",
    image: "https://picsum.photos/seed/cargopants/400/300",
    localImageName: "cargo-pants.jpg",
    standardColors: ["Olive Green", "Black", "Khaki", "Charcoal", "Dark Navy"],
    colorImages: {},
  },
  {
    id: 18,
    name: "Knitwear and Cardigans",
    category: "Apparel",
    subCategory: "Knitwear",
    price: "$34.99",
    image: "https://picsum.photos/seed/cardigan/400/300",
    localImageName: "knitwear-and-cardigans.jpg",
    standardColors: ["Oatmeal", "Charcoal", "Camel", "Dusty Blue", "Burgundy"],
    colorImages: {},
  },
  // ============================================================
  // UNIFORM & WORKWEAR COLLECTION
  // ============================================================
  // ── Industrial Workwear ─────────────────────────────────────
  {
    id: 19,
    name: "Coveralls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$49.99",
    image: "https://picsum.photos/seed/coveralls/400/300",
    localImageName: "coveralls.jpg",
    standardColors: ["Navy Blue", "Royal Blue", "Khaki", "Charcoal", "Safety Orange"],
    colorImages: {},
  },
  {
    id: 20,
    name: "Overalls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$44.99",
    image: "https://picsum.photos/seed/overalls/400/300",
    localImageName: "overalls.jpg",
    standardColors: ["Denim Blue", "Black", "Khaki", "Olive Green", "Navy Blue"],
    colorImages: {},
  },
  {
    id: 21,
    name: "Industrial Work Shirts",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$27.99",
    image: "https://picsum.photos/seed/workshirt/400/300",
    localImageName: "industrial-work-shirts.jpg",
    standardColors: ["Navy Blue", "Royal Blue", "Khaki", "Grey", "Safety Orange"],
    colorImages: {},
  },
  {
    id: 22,
    name: "Work Trousers",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$34.99",
    image: "https://picsum.photos/seed/worktrousers/400/300",
    localImageName: "work-trousers.jpg",
    standardColors: ["Navy Blue", "Black", "Khaki", "Charcoal", "Dark Grey"],
    colorImages: {},
  },
  {
    id: 23,
    name: "Cargo Pants",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$36.99",
    image: "https://picsum.photos/seed/workcargo/400/300",
    localImageName: "workwear-cargo-pants.jpg",
    standardColors: ["Black", "Navy Blue", "Khaki", "Olive Green", "Charcoal"],
    colorImages: {},
  },
  {
    id: 24,
    name: "Bib Overalls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$42.99",
    image: "https://picsum.photos/seed/biboverall/400/300",
    localImageName: "bib-overalls.jpg",
    standardColors: ["Denim Blue", "Navy Blue", "Black", "Khaki", "Safety Orange"],
    colorImages: {},
  },
  {
    id: 25,
    name: "Mechanic Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$54.99",
    image: "https://picsum.photos/seed/mechanicuniform/400/300",
    localImageName: "mechanic-uniforms.jpg",
    standardColors: ["Dark Navy", "Black", "Grey", "Royal Blue", "Charcoal"],
    colorImages: {},
  },
  {
    id: 26,
    name: "Fire-Retardant (FR) Coveralls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$89.99",
    image: "https://picsum.photos/seed/frcoverall/400/300",
    localImageName: "fire-retardant-coveralls.jpg",
    standardColors: ["Navy Blue", "Khaki", "Safety Orange", "Royal Blue", "Charcoal"],
    colorImages: {},
  },
  {
    id: 27,
    name: "Welding Jackets",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$64.99",
    image: "https://picsum.photos/seed/weldingjacket/400/300",
    localImageName: "welding-jackets.jpg",
    standardColors: ["Black", "Dark Navy", "Brown Leather", "Charcoal", "Dark Grey"],
    colorImages: {},
  },
  {
    id: 28,
    name: "Welding Trousers",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    price: "$54.99",
    image: "https://picsum.photos/seed/weldingtrousers/400/300",
    localImageName: "welding-trousers.jpg",
    standardColors: ["Black", "Dark Navy", "Charcoal", "Dark Grey", "Khaki"],
    colorImages: {},
  },
  // ── Hospitality Uniforms ────────────────────────────────────
  {
    id: 29,
    name: "Hotel Staff Suiting",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    price: "$79.99",
    image: "https://picsum.photos/seed/hotelstaff/400/300",
    localImageName: "hotel-staff-suiting.jpg",
    standardColors: ["Black", "Charcoal", "Navy Blue", "Dark Burgundy", "Ivory White"],
    colorImages: {},
  },
  {
    id: 30,
    name: "Chef Coats and Jackets",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    price: "$34.99",
    image: "https://picsum.photos/seed/chefcoat/400/300",
    localImageName: "chef-coats-and-jackets.jpg",
    standardColors: ["White", "Black", "Charcoal", "Royal Blue", "Burgundy"],
    colorImages: {},
  },
  {
    id: 31,
    name: "Chef Aprons",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    price: "$18.99",
    image: "https://picsum.photos/seed/chefapron/400/300",
    localImageName: "chef-aprons.jpg",
    standardColors: ["Black", "White", "Striped Navy", "Dark Green", "Burgundy"],
    colorImages: {},
  },
  {
    id: 32,
    name: "Housekeeping Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    price: "$39.99",
    image: "https://picsum.photos/seed/housekeeping/400/300",
    localImageName: "housekeeping-uniforms.jpg",
    standardColors: ["Pale Blue", "White", "Black", "Teal", "Lavender"],
    colorImages: {},
  },
  {
    id: 33,
    name: "Waiter and Restaurant Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    price: "$44.99",
    image: "https://picsum.photos/seed/waiteruniform/400/300",
    localImageName: "waiter-and-restaurant-uniforms.jpg",
    standardColors: ["Black", "White", "Navy Blue", "Burgundy", "Forest Green"],
    colorImages: {},
  },
  // ── Medical Uniforms ────────────────────────────────────────
  {
    id: 34,
    name: "Lab Coats",
    category: "Uniform & Workwear",
    subCategory: "Medical Uniforms",
    price: "$29.99",
    image: "https://picsum.photos/seed/labcoat/400/300",
    localImageName: "lab-coats.jpg",
    standardColors: ["White", "Off-White", "Pale Blue", "Pale Pink", "Light Grey"],
    colorImages: {},
  },
  {
    id: 35,
    name: "Medical Scrubs",
    category: "Uniform & Workwear",
    subCategory: "Medical Uniforms",
    price: "$27.99",
    image: "https://picsum.photos/seed/medicalscrubs/400/300",
    localImageName: "medical-scrubs.jpg",
    standardColors: ["Ceil Blue", "Navy Blue", "Hunter Green", "Charcoal", "Burgundy"],
    colorImages: {},
  },
  // ── Corporate Uniforms ──────────────────────────────────────
  {
    id: 36,
    name: "Safari Suits",
    category: "Uniform & Workwear",
    subCategory: "Corporate Uniforms",
    price: "$69.99",
    image: "https://picsum.photos/seed/safarisuit/400/300",
    localImageName: "safari-suits.jpg",
    standardColors: ["Khaki", "Beige", "Olive Green", "Stone", "Sand"],
    colorImages: {},
  },
  {
    id: 37,
    name: "Corporate Uniforms and Blazers",
    category: "Uniform & Workwear",
    subCategory: "Corporate Uniforms",
    price: "$89.99",
    image: "https://picsum.photos/seed/corporateblazers/400/300",
    localImageName: "corporate-uniforms-and-blazers.jpg",
    standardColors: ["Navy Blue", "Charcoal", "Black", "Royal Blue", "Mid Grey"],
    colorImages: {},
  },
  // ── Safety Wear ─────────────────────────────────────────────
  {
    id: 38,
    name: "High Visibility (Hi-Vis) Jackets",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    price: "$34.99",
    image: "https://picsum.photos/seed/hivisjacket/400/300",
    localImageName: "hi-vis-jackets.jpg",
    standardColors: ["Safety Yellow", "Safety Orange", "Lime Green", "Red", "Pink Hi-Vis"],
    colorImages: {},
  },
  {
    id: 39,
    name: "Security Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    price: "$59.99",
    image: "https://picsum.photos/seed/securityuniform/400/300",
    localImageName: "security-uniforms.jpg",
    standardColors: ["Black", "Dark Navy", "Charcoal", "Midnight Blue", "Dark Olive"],
    colorImages: {},
  },
  {
    id: 40,
    name: "Reflective Safety Vests",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    price: "$14.99",
    image: "https://picsum.photos/seed/safetyvest/400/300",
    localImageName: "reflective-safety-vests.jpg",
    standardColors: ["Safety Yellow", "Safety Orange", "Lime Green", "Red", "Blue"],
    colorImages: {},
  },
  {
    id: 41,
    name: "Rain Suits and Waterproof Jackets",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    price: "$49.99",
    image: "https://picsum.photos/seed/rainsuit/400/300",
    localImageName: "rain-suits-and-waterproof-jackets.jpg",
    standardColors: ["Safety Yellow", "Safety Orange", "Navy Blue", "Black", "Red"],
    colorImages: {},
  },
  {
    id: 42,
    name: "Caps and Headwear",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    price: "$12.99",
    image: "https://picsum.photos/seed/workheadwear/400/300",
    localImageName: "caps-and-headwear.jpg",
    standardColors: ["Black", "Navy Blue", "Safety Yellow", "White", "Royal Blue"],
    colorImages: {},
  },
  // ============================================================
  // SPORTSWEAR COLLECTION
  // ============================================================
  // ── Teamwear ────────────────────────────────────────────────
  {
    id: 43,
    name: "Football Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$29.99",
    image: "https://picsum.photos/seed/footballjersey/400/300",
    localImageName: "football-jerseys.jpg",
    standardColors: ["Royal Blue", "Red", "White", "Black", "Vibrant Yellow"],
    colorImages: {},
  },
  {
    id: 44,
    name: "Basketball Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$27.99",
    image: "https://picsum.photos/seed/basketballjersey/400/300",
    localImageName: "basketball-jerseys.jpg",
    standardColors: ["Red", "Black", "Royal Blue", "Purple", "Gold"],
    colorImages: {},
  },
  {
    id: 45,
    name: "Baseball Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$31.99",
    image: "https://picsum.photos/seed/baseballjersey/400/300",
    localImageName: "baseball-jerseys.jpg",
    standardColors: ["White", "Pinstripe White", "Grey", "Red", "Navy Blue"],
    colorImages: {},
  },
  {
    id: 46,
    name: "Soccer Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$29.99",
    image: "https://picsum.photos/seed/soccerjersey/400/300",
    localImageName: "soccer-jerseys.jpg",
    standardColors: ["Royal Blue", "Red", "White", "Vibrant Green", "Black"],
    colorImages: {},
  },
  {
    id: 47,
    name: "Cricket Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$26.99",
    image: "https://picsum.photos/seed/cricketjersey/400/300",
    localImageName: "cricket-jerseys.jpg",
    standardColors: ["White", "Sky Blue", "Vibrant Yellow", "Vibrant Green", "Navy Blue"],
    colorImages: {},
  },
  {
    id: 48,
    name: "Rugby Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$34.99",
    image: "https://picsum.photos/seed/rugbyjersey/400/300",
    localImageName: "rugby-jerseys.jpg",
    standardColors: ["Maroon", "Black", "Royal Blue", "Red", "Vibrant Green"],
    colorImages: {},
  },
  {
    id: 49,
    name: "Volleyball Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$24.99",
    image: "https://picsum.photos/seed/volleyballjersey/400/300",
    localImageName: "volleyball-jerseys.jpg",
    standardColors: ["Royal Blue", "Red", "Vibrant Yellow", "White", "Black"],
    colorImages: {},
  },
  {
    id: 50,
    name: "Cycling Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$39.99",
    image: "https://picsum.photos/seed/cyclingjersey/400/300",
    localImageName: "cycling-jerseys.jpg",
    standardColors: ["Neon Yellow", "Neon Orange", "Royal Blue", "Red", "Black"],
    colorImages: {},
  },
  {
    id: 51,
    name: "Sleeveless Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$19.99",
    image: "https://picsum.photos/seed/sleevelessjersey/400/300",
    localImageName: "sleeveless-jerseys.jpg",
    standardColors: ["Royal Blue", "Red", "Black", "White", "Gold"],
    colorImages: {},
  },
  {
    id: 52,
    name: "Teamwear Sets",
    category: "Sportswear",
    subCategory: "Teamwear",
    price: "$54.99",
    image: "https://picsum.photos/seed/teamwearset/400/300",
    localImageName: "teamwear-sets.jpg",
    standardColors: ["Royal Blue", "Red", "Black", "White", "Forest Green"],
    colorImages: {},
  },
  // ── Training Wear ───────────────────────────────────────────
  {
    id: 53,
    name: "Compression Shirts",
    category: "Sportswear",
    subCategory: "Training Wear",
    price: "$22.99",
    image: "https://picsum.photos/seed/compressionshirt/400/300",
    localImageName: "compression-shirts.jpg",
    standardColors: ["Black", "Navy Blue", "Royal Blue", "Charcoal", "White"],
    colorImages: {},
  },
  {
    id: 54,
    name: "Compression Tights and Leggings",
    category: "Sportswear",
    subCategory: "Training Wear",
    price: "$24.99",
    image: "https://picsum.photos/seed/compressiontights/400/300",
    localImageName: "compression-tights-and-leggings.jpg",
    standardColors: ["Black", "Navy Blue", "Charcoal", "Electric Blue", "Burgundy"],
    colorImages: {},
  },
  {
    id: 55,
    name: "Training T-Shirts",
    category: "Sportswear",
    subCategory: "Training Wear",
    price: "$17.99",
    image: "https://picsum.photos/seed/trainingtee/400/300",
    localImageName: "training-t-shirts.jpg",
    standardColors: ["Royal Blue", "Black", "Neon Green", "Red", "White"],
    colorImages: {},
  },
  {
    id: 56,
    name: "Tank Tops",
    category: "Sportswear",
    subCategory: "Training Wear",
    price: "$14.99",
    image: "https://picsum.photos/seed/sportytank/400/300",
    localImageName: "sporty-tank-tops.jpg",
    standardColors: ["Black", "Royal Blue", "Red", "Neon Yellow", "White"],
    colorImages: {},
  },
  {
    id: 57,
    name: "Warm-Up Suits",
    category: "Sportswear",
    subCategory: "Training Wear",
    price: "$49.99",
    image: "https://picsum.photos/seed/warmupsuit/400/300",
    localImageName: "warm-up-suits.jpg",
    standardColors: ["Navy Blue", "Black", "Royal Blue", "Red", "Forest Green"],
    colorImages: {},
  },
  {
    id: 58,
    name: "Running Shorts",
    category: "Sportswear",
    subCategory: "Training Wear",
    price: "$16.99",
    image: "https://picsum.photos/seed/runningshorts/400/300",
    localImageName: "running-shorts.jpg",
    standardColors: ["Black", "Royal Blue", "Neon Orange", "Red", "White"],
    colorImages: {},
  },
  // ── Performance Wear ────────────────────────────────────────
  {
    id: 59,
    name: "Performance Polo Shirts",
    category: "Sportswear",
    subCategory: "Performance Wear",
    price: "$26.99",
    image: "https://picsum.photos/seed/performancepolo/400/300",
    localImageName: "performance-polo-shirts.jpg",
    standardColors: ["Royal Blue", "White", "Black", "Red", "Navy Blue"],
    colorImages: {},
  },
  // ── Athleisure Wear ─────────────────────────────────────────
  {
    id: 60,
    name: "Hoodies",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    price: "$34.99",
    image: "/src/assets/Hoodie black.png",
    localImageName: "athleisure-hoodies.jpg",
    standardColors: ["Black", "Grey Melange", "Navy Blue", "Neon Green", "Burgundy"],
    colorImages: {
      "Black": "/src/assets/Hoodie black.png"
    },
  },
  {
    id: 61,
    name: "Sweatshirts",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    price: "$28.99",
    image: "https://picsum.photos/seed/athleticsweat/400/300",
    localImageName: "athleisure-sweatshirts.jpg",
    standardColors: ["Grey Melange", "Black", "Navy Blue", "Pale Lilac", "Forest Green"],
    colorImages: {},
  },
  {
    id: 62,
    name: "Jackets",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    price: "$44.99",
    image: "https://picsum.photos/seed/athleticjacket/400/300",
    localImageName: "athleisure-jackets.jpg",
    standardColors: ["Black", "Navy Blue", "Neon Yellow", "Royal Blue", "Charcoal"],
    colorImages: {},
  },
  {
    id: 63,
    name: "Tracksuits",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    price: "$59.99",
    image: "https://picsum.photos/seed/tracksuit/400/300",
    localImageName: "tracksuits.jpg",
    standardColors: ["Black", "Navy Blue", "Royal Blue", "Red", "Grey Melange"],
    colorImages: {},
  },
  {
    id: 64,
    name: "Shorts",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    price: "$18.99",
    image: "https://picsum.photos/seed/athshorts/400/300",
    localImageName: "athleisure-shorts.jpg",
    standardColors: ["Black", "Navy Blue", "Grey Melange", "Neon Orange", "Forest Green"],
    colorImages: {},
  },
  {
    id: 65,
    name: "Track Pants",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    price: "$29.99",
    image: "https://picsum.photos/seed/trackpants/400/300",
    localImageName: "track-pants.jpg",
    standardColors: ["Black", "Navy Blue", "Grey Melange", "Royal Blue", "Forest Green"],
    colorImages: {},
  },
];

export function getProductColorImage(product, color) {
  if (!product || !product.colorImages || !color) return null;
  const target = color.trim().toLowerCase();
  const matchedKey = Object.keys(product.colorImages).find(
    k => k.trim().toLowerCase() === target
  );
  return matchedKey ? product.colorImages[matchedKey] : null;
}

export default catalogData;
