// ============================================================
// CatalogData.js
// B2B Merchandising Catalog — 65 Products
// Categories: Apparel | Uniform & Workwear | Sportswear
// Standard Colors: Navy Blue | Black | Burgundy | White | Grey
// ============================================================

const STANDARD_COLORS = ["Navy Blue", "Black", "Burgundy", "White", "Grey"];

export const catalogData = [
  // ============================================================
  // APPAREL COLLECTION
  // ============================================================
  // ── Casual Wear ─────────────────────────────────────────────
  {
    id: 1,
    name: "Hoodies",
    category: "Apparel",
    subCategory: "Casual Wear",
    image: "/assets/hoodie black.jpeg",
    localImageName: "hoodie black.jpeg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":    "/assets/hoodie black.jpeg",
      "Burgundy": "/assets/hoodie burgendy.jpeg",
      "White":    "/assets/hoodie white.jpeg",
    },
    description: "Heavyweight 80/20 cotton-polyester pullover with a double-lined drawstring hood, kangaroo pocket, and ribbed cuffs. Pre-shrunk for wash stability. A premium branding canvas for corporate casual, retail, and team programs.",
  },
  {
    id: 2,
    name: "T-Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    image: "https://picsum.photos/seed/casualtshirt/400/300",
    localImageName: "t-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Ring-spun combed cotton crew-neck with taped neck seams for lasting shape retention. Pre-shrunk and print-ready for plastisol, discharge, and embroidery decoration. The definitive uniform base layer for branded retail and staff programs.",
  },
  {
    id: 3,
    name: "Polo Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    image: "https://picsum.photos/seed/casualpolo/400/300",
    localImageName: "polo-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Structured piqué polo with a three-button placket, moisture-wicking fabric, and a side-vented hem for professional ease of movement. Collar holds its form through rigorous laundering. Ideal for corporate gifting, hospitality, and golf programs.",
  },
  {
    id: 4,
    name: "Long Sleeve T-Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    image: "https://picsum.photos/seed/longsleeve/400/300",
    localImageName: "long-sleeve-t-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Soft-combed cotton long-sleeve jersey with flatlock sleeve seams and ribbed cuffs that hold their shape through repeated washing. Clean surface for screen print and embroidery decoration. Ideal for seasonal uniform and branded outdoor collections.",
  },
  {
    id: 5,
    name: "Henley Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    image: "https://picsum.photos/seed/henleyshirt/400/300",
    localImageName: "henley-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Relaxed-fit cotton-modal henley with a three-button placket and a ribbed collar that retains structure through high-frequency laundering. Delivers a step above the standard tee without added formality. Perfect for smart-casual uniform and lifestyle brand programs.",
  },
  {
    id: 6,
    name: "Zip-Up Hoodies",
    category: "Apparel",
    subCategory: "Casual Wear",
    image: "https://picsum.photos/seed/zipuphoodie/400/300",
    localImageName: "zip-up-hoodies.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Full-zip hoodie with a YKK zipper, brushed fleece interior, and contoured panel seaming for a modern silhouette. Dual hand pockets and a double-lined drawstring hood complete the build. A wardrobe staple for team kits and branded lifestyle collections.",
  },
  {
    id: 7,
    name: "Casual Shirts",
    category: "Apparel",
    subCategory: "Casual Wear",
    image: "https://picsum.photos/seed/casualshirt/400/300",
    localImageName: "casual-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Soft woven poplin button-up with a spread collar, straight hem, and adjustable button cuffs for smart-casual wear. Tailored back yoke provides a refined silhouette for tucked or untucked styling. Available for chest and cuff embroidery branding.",
  },
  // ── Loungewear ──────────────────────────────────────────────
  {
    id: 8,
    name: "Sweatshirts",
    category: "Apparel",
    subCategory: "Loungewear",
    image: "/assets/White sweatshirt.png",
    localImageName: "sweatshirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "White": "/assets/White sweatshirt.png",
    },
    description: "350gsm cotton-polyester fleece crew-neck with a brushed interior and set-in sleeves for a clean, structured silhouette. Ribbed collar, cuffs, and hem ensure shape retention through institutional laundering. A premium surface for embroidery and screen-print decoration.",
  },
  {
    id: 9,
    name: "Fleece Trousers / Joggers",
    category: "Apparel",
    subCategory: "Loungewear",
    image: "https://picsum.photos/seed/fleecejogger/400/300",
    localImageName: "fleece-trousers-joggers.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Tapered jogger in a brushed cotton-polyester fleece with an elasticated drawstring waistband and side pockets. Available with deep zipped pockets for active or streetwear applications. Designed for team loungewear and private-label leisure collections.",
  },
  {
    id: 10,
    name: "Sweatpants",
    category: "Apparel",
    subCategory: "Loungewear",
    image: "https://picsum.photos/seed/sweatpants/400/300",
    localImageName: "sweatpants.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Straight-cut fleece sweatpant with ribbed ankle cuffs, side and rear pockets, and a wide elasticated drawstring waistband. Pre-shrunk fabric maintains texture through high-frequency laundering. Suited for team and staff loungewear programs.",
  },
  {
    id: 11,
    name: "Shorts",
    category: "Apparel",
    subCategory: "Loungewear",
    image: "https://picsum.photos/seed/casualshorts/400/300",
    localImageName: "shorts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Lightweight cotton-blend pull-on short with an elasticated drawstring waist and clean-finished hem. Side pockets and a minimal design offer a clean canvas for embroidery or heat transfer decoration. Versatile for gym wear, summer uniforms, and retail basics.",
  },
  {
    id: 12,
    name: "Tank Tops",
    category: "Apparel",
    subCategory: "Loungewear",
    image: "https://picsum.photos/seed/tanktop/400/300",
    localImageName: "tank-tops.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Fine-ribbed combed cotton sleeveless tank available in a standard or racerback cut with a clean taped neckline. Excellent breathability for warm-climate and active wear contexts. Suited for gym collections, hospitality layering, and athlete uniform programs.",
  },
  {
    id: 13,
    name: "Pyjamas and Loungewear",
    category: "Apparel",
    subCategory: "Loungewear",
    image: "https://picsum.photos/seed/pyjamas/400/300",
    localImageName: "pyjamas-and-loungewear.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Cotton-modal two-piece loungewear set with a V-neck top and elasticated drawstring trousers in coordinated colorways. Skin-friendly and suitable for extended wear. Designed for luxury hotel amenity gifting, wellness brands, and upscale retail.",
  },
  // ── Knitwear ────────────────────────────────────────────────
  {
    id: 14,
    name: "Jackets",
    category: "Apparel",
    subCategory: "Knitwear",
    image: "https://picsum.photos/seed/casualjacket/400/300",
    localImageName: "jackets.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Structured woven-shell jacket with quilted or bonded fleece interior, full front zip, welt hand pockets, and inner security pocket. Clean-cut design suited for branded lifestyle and corporate gifting programs. Custom lining print and embroidered chest branding available.",
  },
  {
    id: 15,
    name: "Vests",
    category: "Apparel",
    subCategory: "Knitwear",
    image: "https://picsum.photos/seed/knitwear vest/400/300",
    localImageName: "vests.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Fine-gauge ribbed knitwear vest with a structured V-neckline that layers effortlessly over shirts and tees. Available with zip or button front in vest or gilet styles. Suited for hospitality, events, and smart-casual uniform collections.",
  },
  {
    id: 16,
    name: "Chinos and Casual Trousers",
    category: "Apparel",
    subCategory: "Knitwear",
    image: "https://picsum.photos/seed/chinotrousers/400/300",
    localImageName: "chinos-and-casual-trousers.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Mid-rise slim-fit chino in 97/3 cotton-elastane stretch twill with flat-front construction and clean pockets. Sharp crease line and all-day stretch comfort for client-facing corporate environments. The cornerstone of business-casual uniform wardrobes.",
  },
  {
    id: 17,
    name: "Cargo Pants",
    category: "Apparel",
    subCategory: "Knitwear",
    image: "https://picsum.photos/seed/cargopants/400/300",
    localImageName: "cargo-pants.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Utility cargo trouser with multiple bellows pockets, reinforced belt loops, and bar-tacked stress points. Available in relaxed or contemporary tapered silhouettes. Designed for workwear-adjacent casual lines, outdoor collections, and field operations.",
  },
  {
    id: 18,
    name: "Knitwear and Cardigans",
    category: "Apparel",
    subCategory: "Knitwear",
    image: "https://picsum.photos/seed/cardigan/400/300",
    localImageName: "knitwear-and-cardigans.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Fine merino-blend open-front cardigan with ribbed cuffs and hem, available with button or zip front options. Breathable warmth suited to temperature-controlled professional environments. A refined layering piece for corporate gifting and hospitality programs.",
  },
  // ============================================================
  // UNIFORM & WORKWEAR COLLECTION
  // ============================================================
  // ── Industrial Workwear ─────────────────────────────────────
  {
    id: 19,
    name: "Coveralls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/coveralls/400/300",
    localImageName: "coveralls.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "One-piece 65/35 poly-cotton twill coverall with a brass-hardware zip, reinforced knees and elbows, and multiple utility pockets. Engineered for industrial site demands with corporate embroidery capability at chest and back. Available in bulk from 50-unit minimum orders.",
  },
  {
    id: 20,
    name: "Overalls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/overalls/400/300",
    localImageName: "overalls.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Heavy cotton-canvas bib-and-brace overall with metal-clasp adjustable straps, hammer loops, and ample cargo pockets. Reinforced knee area for extended garment life. Trusted across construction, agriculture, and industrial manufacturing sectors.",
  },
  {
    id: 21,
    name: "Industrial Work Shirts",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/workshirt/400/300",
    localImageName: "industrial-work-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Long-sleeve 65/35 poly-cotton work shirt with a concealed button placket, pen-divider chest pocket, and collar options. Engineered to carry high-stitch embroidery through commercial laundering without bleed or shrinkage. The foundational piece for industrial and maintenance uniform programs.",
  },
  {
    id: 22,
    name: "Work Trousers",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/worktrousers/400/300",
    localImageName: "work-trousers.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Mechanical-stretch twill work trouser with articulated knees, multiple tool pockets, and heavy-duty belt loops. Bar-tacked stress points extend garment life through daily intensive wear. The everyday foundation of any industrial or trade uniform program.",
  },
  {
    id: 23,
    name: "Cargo Pants",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/workcargo/400/300",
    localImageName: "workwear-cargo-pants.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Heavy-duty workwear cargo trouser with reinforced knees, multiple secure bellows pockets, and triple-needle seam construction. Designed for logistics, construction, and field operations requiring robust utility. Compatible with team embroidery branding programs.",
  },
  {
    id: 24,
    name: "Bib Overalls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/biboverall/400/300",
    localImageName: "bib-overalls.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Heavy cotton-canvas bib overall with hammer loops, carpenter pockets, and adjustable metal-buckle shoulder straps. The wide bib provides excellent branding real estate for embroidered logos. Trusted across construction, carpentry, and industrial manufacturing.",
  },
  {
    id: 25,
    name: "Mechanic Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/mechanicuniform/400/300",
    localImageName: "mechanic-uniforms.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Durable poly-cotton two-piece mechanic uniform with an oil-resistant finish, multi-pocket design, and reinforced stress points. Contrast topstitching delivers professional branding impact. Suited for automotive, engineering, and manufacturing operations.",
  },
  {
    id: 26,
    name: "Fire-Retardant (FR) Coveralls",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/frcoverall/400/300",
    localImageName: "fire-retardant-coveralls.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Arc-rated FR coverall meeting EN ISO 11612 standards in an inherently non-melting FR cotton or modacrylic blend. Antistatic properties reduce ignition risk in explosive atmospheres. Designed for oil and gas, petrochemical, and electrical utilities operations.",
  },
  {
    id: 27,
    name: "Welding Jackets",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/weldingjacket/400/300",
    localImageName: "welding-jackets.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Split cowhide leather or FR cotton welding jacket with a stand-up collar, reinforced stress stitching, and optional Nomex inner lining. Certified protection against welding spatter, arc flash, and radiant heat. Compliant with EN ISO 11611 welding protection standards.",
  },
  {
    id: 28,
    name: "Welding Trousers",
    category: "Uniform & Workwear",
    subCategory: "Industrial Workwear",
    image: "https://picsum.photos/seed/weldingtrousers/400/300",
    localImageName: "welding-trousers.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Professional welding trousers with split-leather protection panels at the thigh, knee, and lower leg. Heat-resistant thread seams throughout. Designed to complete the full PPE ensemble for EN ISO 11611 Class 1 and 2 environments.",
  },
  // ── Hospitality Uniforms ────────────────────────────────────
  {
    id: 29,
    name: "Hotel Staff Suiting",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    image: "https://picsum.photos/seed/hotelstaff/400/300",
    localImageName: "hotel-staff-suiting.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Tailored poly-viscose two-piece suit with a double-vent jacket and flat-front trousers for a sharp, wrinkle-resistant drape across long service shifts. Designed for concierge, front desk, and management teams representing a property's luxury standard. Embroidered badges and monogramming available.",
  },
  {
    id: 30,
    name: "Chef Coats and Jackets",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    image: "https://picsum.photos/seed/chefcoat/400/300",
    localImageName: "chef-coats-and-jackets.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Traditional double-breasted 65/35 poly-cotton chef coat with knotted fabric buttons and a reversible front for extended service wear. Roll-up buttoned cuffs allow quick adaptation between tasks. Available with custom chest embroidery for restaurant and catering brands.",
  },
  {
    id: 31,
    name: "Chef Aprons",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    image: "https://picsum.photos/seed/chefapron/400/300",
    localImageName: "chef-aprons.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Professional bib or waist apron in heavy canvas or poly-cotton twill with adjustable straps and kangaroo or waist pockets. Soil-release finish facilitates rapid commercial laundering. Available for embroidered restaurant, catering, and hotel brand identification.",
  },
  {
    id: 32,
    name: "Housekeeping Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    image: "https://picsum.photos/seed/housekeeping/400/300",
    localImageName: "housekeeping-uniforms.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Durable soil-release poly-cotton housekeeping uniform in dress or trouser-set configurations with practical pocket placement. Easy-care finish withstands high-frequency commercial laundering without color fade. Designed for hotel, healthcare, and facility management operators.",
  },
  {
    id: 33,
    name: "Waiter and Restaurant Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Hospitality Uniforms",
    image: "https://picsum.photos/seed/waiteruniform/400/300",
    localImageName: "waiter-and-restaurant-uniforms.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Coordinated server uniform set in matched colorways with stretch-panel inserts for ease of service movement. Tailored silhouette suits premium dining and hospitality front-of-house environments. Available with custom embroidery and coordinating tie and apron options.",
  },
  // ── Medical Uniforms ────────────────────────────────────────
  {
    id: 34,
    name: "Lab Coats",
    category: "Uniform & Workwear",
    subCategory: "Medical Uniforms",
    image: "https://picsum.photos/seed/labcoat/400/300",
    localImageName: "lab-coats.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Knee-length soil-release 65/35 poly-cotton lab coat with a pen-divider breast pocket, adjustable back belt, and easy-care finish rated for autoclave laundering. Clean, authoritative presentation for laboratory, pharmacy, and clinical environments. Custom embroidery and patch badge options available.",
  },
  {
    id: 35,
    name: "Medical Scrubs",
    category: "Uniform & Workwear",
    subCategory: "Medical Uniforms",
    image: "https://picsum.photos/seed/medicalscrubs/400/300",
    localImageName: "medical-scrubs.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Lightweight moisture-wicking poly-cotton two-piece scrub set with a V-neck tunic, cargo pockets, and elasticated drawstring trousers. Antimicrobial treatment available for clinical hygiene compliance. The trusted uniform solution for nursing, surgical, and allied health professionals.",
  },
  // ── Corporate Uniforms ──────────────────────────────────────
  {
    id: 36,
    name: "Safari Suits",
    category: "Uniform & Workwear",
    subCategory: "Corporate Uniforms",
    image: "/assets/safari suits navy blue.jpeg",
    localImageName: "safari-suits.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Navy Blue": "/assets/safari suits navy blue.jpeg",
      "Grey":      "/assets/safari suits grey.jpeg",
    },
    description: "Breathable cotton-poly gabardine safari suit with epaulette shoulders, patch pockets, and a button-through front. Polished yet practical for field teams, lodge staff, and outdoor event professionals in warm climates. Embroidered insignia on epaulettes and chest pocket available.",
  },
  {
    id: 37,
    name: "Corporate Uniforms and Blazers",
    category: "Uniform & Workwear",
    subCategory: "Corporate Uniforms",
    image: "https://picsum.photos/seed/corporateblazers/400/300",
    localImageName: "corporate-uniforms-and-blazers.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Single-breasted tailored blazer in wrinkle-resistant poly-viscose suiting with a structured welt pocket and clean lapel. Establishes a cohesive, authoritative brand identity for corporate front-of-house and service teams. Custom lining print and embroidered badge options available.",
  },
  // ── Safety Wear ─────────────────────────────────────────────
  {
    id: 38,
    name: "High Visibility (Hi-Vis) Jackets",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    image: "https://picsum.photos/seed/hivisjacket/400/300",
    localImageName: "hi-vis-jackets.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Class 3 hi-vis jacket with 360-degree retro-reflective tape, waterproof outer shell, and a removable quilted inner fleece. Meets EN ISO 20471 certification for road, rail, and construction site operations. Compatible with embroidered company identification within standard compliance guidelines.",
  },
  {
    id: 39,
    name: "Security Uniforms",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    image: "https://picsum.photos/seed/securityuniform/400/300",
    localImageName: "security-uniforms.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Durable poly-wool security uniform set with a structured shirt, epaulette loops for rank insignia, and reinforced-waist trousers. Projects authority and brand consistency for guarding and event stewarding operations. Coordinating tie, belt, and badge programs available.",
  },
  {
    id: 40,
    name: "Reflective Safety Vests",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    image: "https://picsum.photos/seed/safetyvest/400/300",
    localImageName: "reflective-safety-vests.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Lightweight EN ISO 20471 Class 2 compliant safety vest with retro-reflective tape, multiple secure pockets, and adjustable side straps. Breakaway release options available for safety-critical applications. Compatible with printed and embroidered branding within EN standard guidelines.",
  },
  {
    id: 41,
    name: "Rain Suits and Waterproof Jackets",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    image: "https://picsum.photos/seed/rainsuit/400/300",
    localImageName: "rain-suits-and-waterproof-jackets.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Fully seam-sealed PU-coated nylon rain suit with taped seams, adjustable storm cuffs, and a packable hood. Breathable inner membrane prevents moisture buildup during active wear. Available with hi-vis panels and reflective tape for combined safety and weather protection.",
  },
  {
    id: 42,
    name: "Caps and Headwear",
    category: "Uniform & Workwear",
    subCategory: "Safety Wear",
    image: "https://picsum.photos/seed/workheadwear/400/300",
    localImageName: "caps-and-headwear.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Six-panel structured work cap in twill, mesh-back, or brushed cotton with snapback or fitted closure. Front panel accepts up to 10,000-stitch embroidery for premium branding impact. Suited for corporate gifting, events, and large-team uniform headwear programs.",
  },
  // ============================================================
  // SPORTSWEAR COLLECTION
  // ============================================================
  // ── Teamwear ────────────────────────────────────────────────
  {
    id: 43,
    name: "Football Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/football-volleyball-rugby jerseys navy blue.jpeg",
    localImageName: "football-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Navy Blue": "/assets/football-volleyball-rugby jerseys navy blue.jpeg",
      "Black":     "/assets/football-volleyball-rugby jerseys black.jpeg",
      "Burgundy":  "/assets/football-volleyball-rugby jerseys burgendy.jpeg",
      "White":     "/assets/football-volleyball-rugby jerseys white.jpeg",
    },
    description: "Lightweight dry-fit polyester football jersey with mesh ventilation panels and a sublimation-ready surface for full photographic-quality strip printing. Rib-knit v-collar and reinforced armhole binding for lasting structural integrity. Available for complete custom strip programs including crest, sponsor, and player identification.",
  },
  {
    id: 44,
    name: "Basketball Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/basketball navy blue.jpeg",
    localImageName: "basketball-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Navy Blue": "/assets/basketball navy blue.jpeg",
      "Black":     "/assets/basketball black.jpeg",
      "Burgundy":  "/assets/basketball burgendy.jpeg",
      "White":     "/assets/basketball white.jpeg",
    },
    description: "Sleeveless micro-mesh polyester basketball jersey with deep armhole cuts for unrestricted movement and reinforced neck and armhole binding. Full sublimation printing capability for complete club and academy strip customization. Engineered for competition-ready, professional presentation.",
  },
  {
    id: 45,
    name: "Baseball Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/baseball navy blue.jpeg",
    localImageName: "baseball-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Navy Blue": "/assets/baseball navy blue.jpeg",
      "Black":     "/assets/baseball black.jpeg",
      "Burgundy":  "/assets/baseball burgendy.jpeg",
      "White":     "/assets/baseball white.jpeg",
    },
    description: "Performance poly-cotton henley baseball jersey with clean raglan sleeves and a self-fabric stand collar for an authentic game-ready silhouette. Available in home white, road grey, and full custom colorways. Compatible with tackle twill or sublimated wordmarks and numbering programs.",
  },
  {
    id: 46,
    name: "Soccer Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/football-volleyball-rugby jerseys navy blue.jpeg",
    localImageName: "soccer-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Navy Blue": "/assets/football-volleyball-rugby jerseys navy blue.jpeg",
      "Black":     "/assets/football-volleyball-rugby jerseys black.jpeg",
      "Burgundy":  "/assets/football-volleyball-rugby jerseys burgendy.jpeg",
      "White":     "/assets/football-volleyball-rugby jerseys white.jpeg",
    },
    description: "Lightweight moisture-wicking polyester soccer jersey with internal v-neck taping and a ventilated back mesh panel. Engineered for full sublimation printing across the entire body. Complete custom strip design capability for club, national, and academy programs.",
  },
  {
    id: 47,
    name: "Cricket Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/cricket jerseys black.jpeg",
    localImageName: "cricket-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black": "/assets/cricket jerseys black.jpeg",
      "White": "/assets/cricket jerseys white.jpeg",
    },
    description: "Breathable poly-cricket ODI-style jersey with a structured button-down placket and built-in UPF 50+ UV protection. Available in long or short sleeve configurations for year-round play. Designed for complete team strip programs with sponsor and player identification.",
  },
  {
    id: 48,
    name: "Rugby Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/Rugby black.jpeg",
    localImageName: "rugby-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/Rugby black.jpeg",
      "White":     "/assets/Rugby white.jpeg",
    },
    description: "Abrasion-resistant polyester-elastane sublimated rugby jersey in a close athletic fit designed to minimize jersey-grabbing. Reinforced collar and shoulder seams handle scrummaging stress. Full squad customization available with club crest, sponsor branding, and player number.",
  },
  {
    id: 49,
    name: "Volleyball Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/football-volleyball-rugby jerseys navy blue.jpeg",
    localImageName: "volleyball-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Navy Blue": "/assets/football-volleyball-rugby jerseys navy blue.jpeg",
      "Black":     "/assets/football-volleyball-rugby jerseys black.jpeg",
      "Burgundy":  "/assets/football-volleyball-rugby jerseys burgendy.jpeg",
      "White":     "/assets/football-volleyball-rugby jerseys white.jpeg",
    },
    description: "Lightweight four-way stretch spandex-blend volleyball jersey with a scoop neck and wide armhole for full overhead range of motion. Sublimation-ready surface for complete team customization. Designed for both indoor court and beach volleyball programs.",
  },
  {
    id: 50,
    name: "Cycling Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "/assets/cycling jerseys navy blue.jpeg",
    localImageName: "cycling-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Navy Blue": "/assets/cycling jerseys navy blue.jpeg",
      "Black":     "/assets/cycling jerseys black.jpeg",
      "Burgundy":  "/assets/cycling jerseys burgendy.jpeg",
      "White":     "/assets/cycling jerseys white.jpeg",
      "Grey":      "/assets/cycling jerseys grey.jpeg",
    },
    description: "Aerodynamic lycra-blend full-zip cycling jersey with three deep rear pockets and a reflective safety strip at the lower back. Engineered to minimize wind resistance during road and competitive cycling. Full sublimation kit customization for club and team programs.",
  },
  {
    id: 51,
    name: "Sleeveless Jerseys",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "https://picsum.photos/seed/sleevelessjersey/400/300",
    localImageName: "sleeveless-jerseys.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Lightweight interlock knit sleeveless sports jersey with reinforced armhole binding for durability across match and laundering stress. Large uninterrupted print surface for sublimation, screen print, and tackle-twill application. Compatible with multi-sport team programs for schools and academies.",
  },
  {
    id: 52,
    name: "Teamwear Sets",
    category: "Sportswear",
    subCategory: "Teamwear",
    image: "https://picsum.photos/seed/teamwearset/400/300",
    localImageName: "teamwear-sets.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Coordinated performance jersey and matching shorts in fabric and colorway-consistent construction, engineered as a complete strip solution. Elastic waistbands with internal drawcord and matching binding tape throughout. Full sublimation custom branding capability across all elements.",
  },
  // ── Training Wear ───────────────────────────────────────────
  {
    id: 53,
    name: "Compression Shirts",
    category: "Sportswear",
    subCategory: "Training Wear",
    image: "/assets/sportswear compression shirts navy blue.jpeg",
    localImageName: "compression-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/sportswear compression shirts black.jpeg",
      "Burgundy":  "/assets/sportswear compression shirts burgendy.jpeg",
      "Grey":      "/assets/sportswear compression shirts grey.jpeg",
      "Navy Blue": "/assets/sportswear compression shirts navy blue.jpeg",
      "White":     "/assets/sportswear compression shirts white.jpeg",
    },
    description: "High-denier elastane-nylon four-way stretch compression shirt with graduated compression zones for muscle activation and fatigue reduction. Flatlock seams eliminate irritation across extended wear. Engineered for elite and amateur athletes in high-intensity training and competition.",
  },
  {
    id: 54,
    name: "Compression Tights and Leggings",
    category: "Sportswear",
    subCategory: "Training Wear",
    image: "/assets/compression tights black.jpeg",
    localImageName: "compression-tights-and-leggings.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/compression tights black.jpeg",
      "Burgundy":  "/assets/compression tights burgendy.jpeg",
      "Navy Blue": "/assets/compression tights many blue.jpeg",
      "White":     "/assets/compression tights white.jpeg",
    },
    description: "Premium performance elastane compression tights with graduated compression from ankle to upper thigh for improved venous return. Flatlock seaming and moisture-wicking inner surface prevent chafing. Designed for both in-session performance and post-session recovery.",
  },
  {
    id: 55,
    name: "Training T-Shirts",
    category: "Sportswear",
    subCategory: "Training Wear",
    image: "https://picsum.photos/seed/trainingtee/400/300",
    localImageName: "training-t-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Dry-fit polyester training tee with a structured crew neck, raglan sleeves, and mesh ventilation inserts for heat dissipation. Compatible with screen print and heat transfer customization for team identification. The dependable everyday training garment for squads and fitness facilities.",
  },
  {
    id: 56,
    name: "Tank Tops",
    category: "Sportswear",
    subCategory: "Training Wear",
    image: "/assets/tanktops black.jpeg",
    localImageName: "sporty-tank-tops.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/tanktops black.jpeg",
      "Burgundy":  "/assets/tank tops burgendy.jpeg",
      "Navy Blue": "/assets/tanktops navy blue.jpeg",
      "White":     "/assets/tanktops white.jpeg",
    },
    description: "Lightweight polyester-spandex performance tank with open mesh side panels and a clean-finished neckline in standard or crossback configurations. Maximum ventilation for gym and field training environments. Designed for fitness brands and branded athlete programs.",
  },
  {
    id: 57,
    name: "Warm-Up Suits",
    category: "Sportswear",
    subCategory: "Training Wear",
    image: "https://picsum.photos/seed/warmupsuit/400/300",
    localImageName: "warm-up-suits.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Full warm-up suit with a mesh-lined zip-through jacket and tapered elasticated trouser in a smooth, pilling-resistant polyester shell. Kangaroo pockets and zip ankles for a polished, functional finish. The essential team identity piece for professional clubs and representative squads.",
  },
  {
    id: 58,
    name: "Running Shorts",
    category: "Sportswear",
    subCategory: "Training Wear",
    image: "https://picsum.photos/seed/runningshorts/400/300",
    localImageName: "running-shorts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {},
    description: "Lightweight 100% polyester running short with a split hem for maximum stride freedom and a built-in moisture-management brief liner. Internal key pocket with zip closure. Designed for running clubs, athletics programs, and endurance event promotional kits.",
  },
  // ── Performance Wear ────────────────────────────────────────
  {
    id: 59,
    name: "Performance Polo Shirts",
    category: "Sportswear",
    subCategory: "Performance Wear",
    image: "/assets/perfomance polos black.jpeg",
    localImageName: "performance-polo-shirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":    "/assets/perfomance polos black.jpeg",
      "Burgundy": "/assets/perfomance polos burgendy.jpeg",
      "White":    "/assets/perfomance polos white.jpeg",
    },
    description: "Technical moisture-wicking piqué polo with a structured collar that holds its form through training and UPF 30+ fabric for outdoor protection. Anti-odor treatment extends freshness between wash cycles. Designed for golf, tennis, and corporate sports programs.",
  },
  // ── Athleisure Wear ─────────────────────────────────────────
  {
    id: 60,
    name: "Hoodies",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    image: "/assets/sportswear hoodies black.jpeg",
    localImageName: "athleisure-hoodies.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/sportswear hoodies black.jpeg",
      "Burgundy":  "/assets/sportswear hoodies burgendy.jpeg",
      "Navy Blue": "/assets/sportswear hoodies navy blue.jpeg",
      "White":     "/assets/sportswear hoodies white.jpeg",
    },
    description: "320gsm garment-dyed cotton-poly fleece athleisure hoodie with a drop-shoulder silhouette, large kangaroo pocket, and brushed interior. Relaxed, oversized construction for an effortless lifestyle aesthetic. Premium branding potential through embroidery and screen print at volume.",
  },
  {
    id: 61,
    name: "Sweatshirts",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    image: "/assets/sportswear sweatshirts black.jpeg",
    localImageName: "athleisure-sweatshirts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/sportswear sweatshirts black.jpeg",
      "Burgundy":  "/assets/sportswear sweatshirts burgendy.jpeg",
      "Grey":      "/assets/sportswear sweatshirts grey.jpeg",
      "Navy Blue": "/assets/sportswear sweatshirts navy blue.jpeg",
      "White":     "/assets/sportswear sweatshirts white.jpeg",
    },
    description: "Midweight garment-dyed cotton fleece crew-neck with raw-cut or classic ribbed hem options for a contemporary or structured finish. Minimal design positions it as a cornerstone piece for athleisure and casual lifestyle collections. Clean canvas for embroidery branding.",
  },
  {
    id: 62,
    name: "Jackets",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    image: "/assets/sportswear jacket black.jpeg",
    localImageName: "athleisure-jackets.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/sportswear jacket black.jpeg",
      "Burgundy":  "/assets/sportswear jacket burgendy.jpeg",
      "Grey":      "/assets/sportswear jacket grey.jpeg",
      "Navy Blue": "/assets/sportswear jacket navy blue.jpeg",
      "White":     "/assets/sportswear jacket white.jpeg",
    },
    description: "Smooth micro-polyester athleisure track jacket with a banded collar, ribbed cuffs, full-zip front, and clean-finish side pockets. Available in fitted athletic and relaxed casual silhouettes. Premium embroidery or sublimated chest panel branding option available.",
  },
  {
    id: 63,
    name: "Tracksuits",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    image: "/assets/tracksuits black.jpeg",
    localImageName: "tracksuits.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/tracksuits black.jpeg",
      "Burgundy":  "/assets/tracksuits burgendyjpeg.jpeg",
      "Grey":      "/assets/tracksuits grey.jpeg",
      "Navy Blue": "/assets/tracksuits navy blue.jpeg",
      "White":     "/assets/tracksuits white.jpeg",
    },
    description: "Premium tricot polyester two-piece tracksuit with a zip-through jacket featuring banded collar and side-panel contrast options, and tapered zip-ankle trousers. A polished squad travel and presentation kit for professional clubs and national programs. Full custom branding at all touchpoints.",
  },
  {
    id: 64,
    name: "Shorts",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    image: "/assets/sportswear shorts black.jpeg",
    localImageName: "athleisure-shorts.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/sportswear shorts black.jpeg",
      "Grey":      "/assets/sportswear shorts grey.jpeg",
      "Navy Blue": "/assets/sportswear shorts navy blue.jpeg",
      "White":     "/assets/sportswear shorts white.jpeg",
    },
    description: "Above-the-knee cotton-terry or performance fabric athleisure short with an elasticated drawstring waistband and side pockets. Bridges gym and street aesthetics for lifestyle brands and branded merchandise programs. Compatible with embroidery and heat transfer decoration.",
  },
  {
    id: 65,
    name: "Track Pants",
    category: "Sportswear",
    subCategory: "Athleisure Wear",
    image: "/assets/sportswear trackpants black.jpeg",
    localImageName: "track-pants.jpg",
    standardColors: STANDARD_COLORS,
    colorImages: {
      "Black":     "/assets/sportswear trackpants black.jpeg",
      "Burgundy":  "/assets/sportswear trackpants burgendy.jpeg",
      "Grey":      "/assets/sportswear trackpants grey.jpeg",
      "Navy Blue": "/assets/sportswear trackpants navy blue.jpeg",
      "White":     "/assets/sportswear trackpants white.jpeg",
    },
    description: "Slim-tapered polyester or cotton-modal track pant with an elasticated drawstring waist, optional zip ankle, and side pockets with taped seam detailing. Designed for athleisure brands requiring a movement-ready trouser with a refined, premium silhouette.",
  },
];

export function getProductColorImage(product, color) {
  if (!product || !product.colorImages || !color) return null;
  const target = color.trim().toLowerCase();
  const matchedKey = Object.keys(product.colorImages).find(
    k => k.trim().toLowerCase() === target
  );
  return matchedKey ? product.colorImages[matchedKey] : null;
}

export function getFallbackApparelImage(name) {
  if (!name) return 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=400&h=300&q=80';
  const n = name.toLowerCase();
  if (n.includes('t-shirt') || n.includes('tee') || n.includes('sleeveless')) {
    return 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('polo')) {
    return 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('shirt')) {
    return 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('hoodie') || n.includes('sweatshirt')) {
    return 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('pant') || n.includes('jogger') || n.includes('trouser') || n.includes('chino') || n.includes('overall') || n.includes('coverall')) {
    return 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('short')) {
    return 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('jacket') || n.includes('blazer') || n.includes('suit') || n.includes('vest')) {
    return 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('scrub') || n.includes('lab coat')) {
    return 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('chef') || n.includes('apron')) {
    return 'https://images.unsplash.com/photo-1577106263724-2c8e03bfe9cf?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('jersey') || n.includes('teamwear')) {
    return 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=400&h=300&q=80';
  }
  if (n.includes('cap') || n.includes('headwear')) {
    return 'https://images.unsplash.com/photo-1589793907316-f94015540e24?auto=format&fit=crop&w=400&h=300&q=80';
  }
  return 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=400&h=300&q=80';
}


export const GLOBAL_MOQ = 50;
export const WHATSAPP_LINK = "https://wa.me/923152262430?text=Hi!%20I'm%20interested%20in%20initiating%20a%20B2B%20apparel%20inquiry.";

export default catalogData;
